import { IUserProfile } from "../shared/model/IUserProfile";
import { Gender } from "../shared/types/Gender";
import { Language } from "../shared/types/Language";
import { Tariff } from "../shared/types/Tariff";
import { uuid } from "../utils/uuid";

export const DummyUserProfiles: IUserProfile[] = [
    {id:uuid(), userId: uuid(), firstname:"Beatriz", lastname:"Bascon-Wolf", gender:Gender.FEMALE, birthday: new Date("04.01.1969"), street:"Anne-Frank-Straße 21", postalCode:"69221", city:"Dossenheim", email:"bascon@gmx.de", phone:"", joinedOn: new Date(), isAdmin: false, createdAt: new Date(), updatedAt: new Date(), language: Language.en, isDeactivated: false, bankAccountOwner: "", bankAccountIBAN: "", bankAccountBIC: "", bankAccountInstitution: "", memberId: "YT0001", tariff: Tariff.PRINCIPALS, gradings: []},
    {id:uuid(), userId: "3d5b322c-71ae-41c6-a336-0976eccca612", firstname:"Frank", lastname:"Burkart", gender:Gender.MALE, birthday: new Date("04.01.1969"), street:"Richard-Wagner-Straße 29", postalCode:"69221", city:"Dossenheim", email:"frank.burkart@hotmail.de", phone:"", joinedOn: new Date(),  isAdmin: true,createdAt: new Date(), updatedAt: new Date(), language: Language.en, isDeactivated: false, bankAccountOwner: "", bankAccountIBAN: "", bankAccountBIC: "", bankAccountInstitution: "", memberId: "YT0002", tariff: Tariff.PRINCIPALS, gradings: []},
    {id:uuid(), userId: uuid(), firstname:"Peter", lastname:"Hoffmann", gender:Gender.MALE, birthday: new Date("04.01.1969"), street:"Jakob-Ruppert-Straße 9", postalCode:"69214", city:"Eppelheim", email:"hoffmannpeter82@gmail.com", phone:"", joinedOn: new Date(),  isAdmin: false,createdAt: new Date(), updatedAt: new Date(), language: Language.en, isDeactivated: false, bankAccountOwner: "", bankAccountIBAN: "", bankAccountBIC: "", bankAccountInstitution: "", memberId: "YT0003", tariff: Tariff.PRINCIPALS, gradings: []},
    {id:uuid(), userId: "b7c64925-3c0b-404d-acac-66f9c5e03ba3", firstname:"Sonja", lastname:"Steinhagen", gender:Gender.FEMALE, birthday: new Date("04.01.1969"), street:"Richard-Wagner-Straße 29", postalCode:"69221", city:"Dossenheim", email:"sonja.steinhagen@gmail.com", phone:"", joinedOn: new Date(),  isAdmin: false,createdAt: new Date(), updatedAt: new Date(), language: Language.en, isDeactivated: false, bankAccountOwner: "", bankAccountIBAN: "", bankAccountBIC: "", bankAccountInstitution: "", memberId: "YT0004", tariff: Tariff.PRINCIPALS, gradings: []},
    {id:uuid(), userId: uuid(), firstname:"Verena", lastname:"Tewes", gender:Gender.FEMALE, birthday: new Date("04.01.1969"), street:"Jakob-Ruppert-Straße 9", postalCode:"69214", city:"Eppelheim", email:"tewes.verena@gmail.com", phone:"", joinedOn: new Date(),  isAdmin: false,createdAt: new Date(), updatedAt: new Date(), language: Language.en, isDeactivated: false, bankAccountOwner: "", bankAccountIBAN: "", bankAccountBIC: "", bankAccountInstitution: "", memberId: "YT0005", tariff: Tariff.RELATIVES, gradings: []},
    {id:uuid(), userId: uuid(), firstname:"Iris", lastname:"Eberle", gender:Gender.FEMALE, birthday: new Date("04.01.1969"), street:"Hans-Pfitzner-Straße 3", postalCode:"69198", city:"Schriesheim", email:"iris_eberle@gmx.de", phone:"", joinedOn: new Date(),  isAdmin: false,createdAt: new Date(), updatedAt: new Date(), language: Language.en, isDeactivated: false, bankAccountOwner: "", bankAccountIBAN: "", bankAccountBIC: "", bankAccountInstitution: "", memberId: "YT0006", tariff: Tariff.TEENAGERS_ADULTS, gradings: []},
    {id:uuid(), userId: uuid(), firstname:"Simon", lastname:"Spiess", gender:Gender.MALE, birthday: new Date("04.01.1969"), street:"Hans-Pfitzner-Straße 3", postalCode:"69198", city:"Schriesheim", email:"", phone:"", joinedOn: new Date(), createdAt: new Date(),  isAdmin: false,updatedAt: new Date(), language: Language.en, isDeactivated: false, bankAccountOwner: "", bankAccountIBAN: "", bankAccountBIC: "", bankAccountInstitution: "", memberId: "YT0007", tariff: Tariff.TEENAGERS_ADULTS, gradings: []},
    {id:uuid(), userId: uuid(), firstname:"Sven", lastname:"Marten", gender:Gender.MALE, birthday: new Date("04.01.1969"), street:"Schulbergweg 3", postalCode:"69115", city:"Heidelberg", email:"sven.marten@mac.com", phone:"", joinedOn: new Date(),  isAdmin: false,createdAt: new Date(), updatedAt: new Date(), language: Language.en, isDeactivated: false, bankAccountOwner: "", bankAccountIBAN: "", bankAccountBIC: "", bankAccountInstitution: "", memberId: "YT0008", tariff: Tariff.TEENAGERS_ADULTS, gradings: []},
    {id:uuid(), userId: uuid(), firstname:"Irina", lastname:"Pfenning", gender:Gender.FEMALE, birthday: new Date("04.01.1969"), street:"Schulbergweg 3", postalCode:"69118", city:"Heidelberg", email:"irina.pfenning@inovis.cc", phone:"", joinedOn: new Date(),  isAdmin: false,createdAt: new Date(), updatedAt: new Date(), language: Language.en, isDeactivated: false, bankAccountOwner: "", bankAccountIBAN: "", bankAccountBIC: "", bankAccountInstitution: "", memberId: "YT0009", tariff: Tariff.TEENAGERS_ADULTS, gradings: []},
    {id:uuid(), userId: uuid(), firstname:"Janne", lastname:"Frenz", gender:Gender.FEMALE, birthday: new Date("04.01.1969"), street:"Rottmanstraße 3", postalCode:"69118", city:"Heidelberg", email:"jnnfrenz@icloud.com", phone:"", joinedOn: new Date(),  isAdmin: false,createdAt: new Date(), updatedAt: new Date(), language: Language.en, isDeactivated: false, bankAccountOwner: "", bankAccountIBAN: "", bankAccountBIC: "", bankAccountInstitution: "", memberId: "YT0010", tariff: Tariff.TRAINEES_STUDENTS_PENSIONERS, gradings: []},
    {id:uuid(), userId: uuid(), firstname:"Anna", lastname:"Doskotz", gender:Gender.FEMALE, birthday: new Date("04.01.1969"), street:"Dossenheimer Landstraße 93", postalCode:"69121", city:"Heidelberg", email:"annadoskotz@gmail.com", phone:"", joinedOn: new Date(),  isAdmin: false,createdAt: new Date(), updatedAt: new Date(), language: Language.en, isDeactivated: false, bankAccountOwner: "", bankAccountIBAN: "", bankAccountBIC: "", bankAccountInstitution: "", memberId: "YT0011", tariff: Tariff.TEENAGERS_ADULTS, gradings: []},
    {id:uuid(), userId: uuid(), firstname:"Annika", lastname:"Breutmann", gender:Gender.FEMALE, birthday: new Date("04.01.1969"), street:"Schröderstraße 9", postalCode:"69121", city:"Heidelberg", email:"annika.breutmann@gmx.de", phone:"", joinedOn: new Date(),  isAdmin: false,createdAt: new Date(), updatedAt: new Date(), language: Language.en, isDeactivated: false, bankAccountOwner: "", bankAccountIBAN: "", bankAccountBIC: "", bankAccountInstitution: "", memberId: "YT0012", tariff: Tariff.TEENAGERS_ADULTS, gradings: []},
    {id:uuid(), userId: uuid(), firstname:"Preeti", lastname:"Purohit", gender:Gender.FEMALE, birthday: new Date("04.01.1969"), street:"Trübnerstraße 8", postalCode:"69120", city:"Heidelberg", email:"purohitpreeti@gmail.com", phone:"", joinedOn: new Date(),  isAdmin: false,createdAt: new Date(), updatedAt: new Date(), language: Language.en, isDeactivated: false, bankAccountOwner: "", bankAccountIBAN: "", bankAccountBIC: "", bankAccountInstitution: "", memberId: "YT0013", tariff: Tariff.TEENAGERS_ADULTS, gradings: []},
    {id:uuid(), userId: uuid(), firstname:"Merlin", lastname:"Böhm", gender:Gender.MALE, birthday: new Date("04.01.1969"), street:"Fritz-Frey-Straße 6", postalCode:"69121", city:"Heidelberg", email:"merlinboehm@gmx.net", phone:"", joinedOn: new Date(),  isAdmin: false,createdAt: new Date(), updatedAt: new Date(), language: Language.en, isDeactivated: false, bankAccountOwner: "", bankAccountIBAN: "", bankAccountBIC: "", bankAccountInstitution: "", memberId: "YT0014", tariff: Tariff.TEENAGERS_ADULTS, gradings: []},
    {id:uuid(), userId: uuid(), firstname:"Charlotte", lastname:"Weidner", gender:Gender.FEMALE, birthday: new Date("04.01.1969"), street:"Rohrbacher Straße 77a", postalCode:"69198", city:"Schriesheim", email:"charlotte.weidner91@gmail.com", phone:"", joinedOn: new Date(), isAdmin: false, createdAt: new Date(), updatedAt: new Date(), language: Language.en, isDeactivated: false, bankAccountOwner: "", bankAccountIBAN: "", bankAccountBIC: "", bankAccountInstitution: "", memberId: "YT0015", tariff: Tariff.TEENAGERS_ADULTS, gradings: []},
    {id:uuid(), userId: uuid(), firstname:"Mark", lastname:"Bahinskyi", gender:Gender.MALE, birthday: new Date("04.01.1969"), street:"Landstraße 106", postalCode:"69121", city:"Heidelberg", email:"13121989k@gmail.com", phone:"", joinedOn: new Date(),  isAdmin: false,createdAt: new Date(), updatedAt: new Date(), language: Language.en, isDeactivated: false, bankAccountOwner: "", bankAccountIBAN: "", bankAccountBIC: "", bankAccountInstitution: "", memberId: "YT0016", tariff: Tariff.CHILDREN, gradings: []},
    {id:uuid(), userId: uuid(), firstname:"Anja", lastname:"Bleck", gender:Gender.FEMALE, birthday: new Date("04.01.1969"), street:"Rohrbacher Straße 73", postalCode:"69115", city:"Heidelberg", email:"anjy.why@gmail.com", phone:"", joinedOn: new Date(),  isAdmin: false,createdAt: new Date(), updatedAt: new Date(), language: Language.en, isDeactivated: false, bankAccountOwner: "", bankAccountIBAN: "", bankAccountBIC: "", bankAccountInstitution: "", memberId: "YT0017", tariff: Tariff.TEENAGERS_ADULTS, gradings: []},
    {id:uuid(), userId: uuid(), firstname:"Philipp", lastname:"Müller", gender:Gender.MALE, birthday: new Date("04.01.1969"), street:"Klappergasse 3", postalCode:"69123", city:"Heidelberg", email:"pem1730@gmx.de", phone:"", joinedOn: new Date(),  isAdmin: false,createdAt: new Date(), updatedAt: new Date(), language: Language.en, isDeactivated: false, bankAccountOwner: "", bankAccountIBAN: "", bankAccountBIC: "", bankAccountInstitution: "", memberId: "YT0018", tariff: Tariff.TEENAGERS_ADULTS, gradings: []},
    {id:uuid(), userId: uuid(), firstname:"Filian", lastname:"Rößler", gender:Gender.MALE, birthday: new Date("04.01.1969"), street:"Lorscher Straße 9a", postalCode:"69198", city:"Schriesheim", email:"christina.roessler80@gmail.com", phone:"", joinedOn: new Date(),  isAdmin: false,createdAt: new Date(), updatedAt: new Date(), language: Language.en, isDeactivated: false, bankAccountOwner: "", bankAccountIBAN: "", bankAccountBIC: "", bankAccountInstitution: "", memberId: "YT0019", tariff: Tariff.CHILDREN, gradings: []},
    {id:uuid(), userId: uuid(), firstname:"Sita", lastname:"Moradi", gender:Gender.FEMALE, birthday: new Date("04.01.1969"), street:"Bollengrubweg 11", postalCode:"69198", city:"Schriesheim", email:"sitamoradi2000@gmail.com", phone:"", joinedOn: new Date(),  isAdmin: false,createdAt: new Date(), updatedAt: new Date(), language: Language.en, isDeactivated: false, bankAccountOwner: "", bankAccountIBAN: "", bankAccountBIC: "", bankAccountInstitution: "", memberId: "YT0020", tariff: Tariff.FAMILY_3, gradings: []},
    {id:uuid(), userId: uuid(), firstname:"Soraya", lastname:"Moradi", gender:Gender.FEMALE, birthday: new Date("04.01.1969"), street:"Bollengrubweg 11", postalCode:"69198", city:"Schriesheim", email:"sitamoradi2000@gmail.com", phone:"", joinedOn: new Date(), isAdmin: false, createdAt: new Date(), updatedAt: new Date(), language: Language.en, isDeactivated: false, bankAccountOwner: "", bankAccountIBAN: "", bankAccountBIC: "", bankAccountInstitution: "", memberId: "YT0021", tariff: Tariff.FAMILY_3, gradings: []},
    {id:uuid(), userId: uuid(), firstname:"Khalida", lastname:"Moradi", gender:Gender.FEMALE, birthday: new Date("04.01.1969"), street:"Bollengrubweg 11", postalCode:"69198", city:"Schriesheim", email:"sitamoradi2000@gmail.com", phone:"", joinedOn: new Date(),  isAdmin: false,createdAt: new Date(), updatedAt: new Date(), language: Language.en, isDeactivated: false, bankAccountOwner: "", bankAccountIBAN: "", bankAccountBIC: "", bankAccountInstitution: "", memberId: "YT0022", tariff: Tariff.FAMILY_3, gradings: []},
    {id:uuid(), userId: uuid(), firstname:"Mokarama", lastname:"Moradi", gender:Gender.FEMALE, birthday: new Date("04.01.1969"), street:"Bollengrubweg 11", postalCode:"69198", city:"Schriesheim", email:"sitamoradi2000@gmail.com", phone:"", joinedOn: new Date(), isAdmin: false, createdAt: new Date(), updatedAt: new Date(), language: Language.en, isDeactivated: false, bankAccountOwner: "", bankAccountIBAN: "", bankAccountBIC: "", bankAccountInstitution: "", memberId: "YT00223", tariff: Tariff.FAMILY_3, gradings: []},
    {id:uuid(), userId: uuid(), firstname:"Max", lastname:"Bäumer", gender:Gender.MALE, birthday: new Date("04.01.1969"), street:"Martin-Stöhr-Straße 3", postalCode:"69493", city:"Hirschberg an der Bergstraße", email:"mpp.baeumer@gmail.com", phone:"", joinedOn: new Date(), isAdmin: false, createdAt: new Date(), updatedAt: new Date(), language: Language.en, isDeactivated: false, bankAccountOwner: "", bankAccountIBAN: "", bankAccountBIC: "", bankAccountInstitution: "", memberId: "YT0024", tariff: Tariff.TEENAGERS_ADULTS, gradings: []},
    {id:uuid(), userId: uuid(), firstname:"Zuzanna", lastname:"Wegrzycka", gender:Gender.FEMALE, birthday: new Date("04.01.1969"), street:"Unterer Weinweg 8", postalCode:"69253", city:"Heiligkreuzsteinach", email:"aduraadura88@gmail.com", phone:"", joinedOn: new Date(), isAdmin: false, createdAt: new Date(), updatedAt: new Date(), language: Language.en, isDeactivated: false, bankAccountOwner: "", bankAccountIBAN: "", bankAccountBIC: "", bankAccountInstitution: "", memberId: "YT0025", tariff: Tariff.CHILDREN, gradings: []},
    {id:uuid(), userId: uuid(), firstname:"Kerstin", lastname:"Godziatkowski", gender:Gender.FEMALE, birthday: new Date("04.01.1969"), street:"Bergheimerstraße 38", postalCode:"69115", city:"Heidelberg", email:"dragontussy@hotmail.de", phone:"", joinedOn: new Date(), isAdmin: false, createdAt: new Date(), updatedAt: new Date(), language: Language.en, isDeactivated: false, bankAccountOwner: "", bankAccountIBAN: "", bankAccountBIC: "", bankAccountInstitution: "", memberId: "YT0026", tariff: Tariff.TEENAGERS_ADULTS, gradings: []},
    {id:uuid(), userId: uuid(), firstname:"Natalie", lastname:"Wendel-Minz", gender:Gender.FEMALE, birthday: new Date("04.01.1969"), street:"Landstraße 84", postalCode:"69198", city:"Schriesheim", email:"Nata-Wendel@gmx.de", phone:"", joinedOn: new Date(), isAdmin: false, createdAt: new Date(), updatedAt: new Date(), language: Language.en, isDeactivated: false, bankAccountOwner: "", bankAccountIBAN: "", bankAccountBIC: "", bankAccountInstitution: "", memberId: "YT0027", tariff: Tariff.TEENAGERS_ADULTS, gradings: []},
    {id:uuid(), userId: uuid(), firstname:"Bianca", lastname:"Maus", gender:Gender.FEMALE, birthday: new Date("04.01.1969"), street:"Ladenburgerstraße 4", postalCode:"69198", city:"Schriesheim", email:"bianca.andrea.maus@gmail.com", phone:"16090429138", joinedOn: new Date(), isAdmin: false, createdAt: new Date(), updatedAt: new Date(), language: Language.en, isDeactivated: false, bankAccountOwner: "", bankAccountIBAN: "", bankAccountBIC: "", bankAccountInstitution: "", memberId: "YT0028", tariff: Tariff.TEENAGERS_ADULTS, gradings: []},
    {id:uuid(), userId: uuid(), firstname:"Charlotte", lastname:"Godziatkowski", gender:Gender.FEMALE, birthday: new Date("04.01.1969"), street:"Ladenburgerstraße 4", postalCode:"69198", city:"Schriesheim", email:"bianca.andrea.maus@gmail.com", phone:"16090429138", joinedOn: new Date(), isAdmin: false, createdAt: new Date(), updatedAt: new Date(), language: Language.en, isDeactivated: false, bankAccountOwner: "", bankAccountIBAN: "", bankAccountBIC: "", bankAccountInstitution: "", memberId: "YT0028", tariff: Tariff.TEENAGERS_ADULTS, gradings: []},
];